### PR TITLE
Add event to add websites with 'Enter'

### PR DESCRIPTION
**Pull request by Judikaelle**
I wanted to improve the user experience. Hopefully I did something good :)

### CODE REVIEW

**Comment by Judikaelle** [comment]
Commit #30  must not be in this PR, right ?

**Comment by Judikaelle** [comment]
I'm not comfortable with git yet but I'm trying to progress. Don't hesitate to tell me if I'm doing something wrong.
@arthureichelberger

**Comment by arthurdotwork** [comment]
> I'm not comfortable with git yet but I'm trying to progress. Don't hesitate to tell me if I'm doing something wrong.
> @arthureichelberger

Don't worry, so far so good! I'll review this after 7pm. :)

**Review by arthurdotwork — APPROVED** [review]

**Comment by arthurdotwork** [comment]
Approved as a Xmas gift! Sorry, I was very busy.

**Pull request merged**
